# WEEK 1 

#### BUILT-IN

In [3]:
name = 'siddhartha bhat'

In [4]:
print('My name is %s and weight is %d' % (name, 50))

My name is siddhartha bhat and weight is 50


In [8]:
string = 'this is an EXAMPLE string'
string.capitalize()

'This is an example string'

In [9]:
string.count('i')

3

In [10]:
string.find('is')

2

In [11]:
string.lower()

'this is an example string'

In [12]:
string.replace('string', 'sentence')

'this is an EXAMPLE sentence'

In [14]:
string.swapcase()

'THIS IS AN example STRING'

In [15]:
string.title()

'This Is An Example String'

#### LIST

In [22]:
lst = ['physics', 'chemistry', 1997, 2000]

del lst[2]

lst

['physics', 'chemistry', 2000]

In [23]:
print(
    'physics' in lst,
    len(lst),
    lst.count('physics')
    )

True 3 1


In [26]:
lst.reverse()
lst

[2000, 'chemistry', 'physics']

#### TUPLE

In [27]:
tp = ('maths', 'physics', 2000, 5000)
tp

('maths', 'physics', 2000, 5000)

In [28]:
tp[3] = 2000

TypeError: 'tuple' object does not support item assignment

In [33]:
age = 18
b = ('kid' if age < 18 else 'adult')
print(b, type(b))

adult <class 'str'>


In [36]:
from math import *
x = [6, 30, 9, 21, 93]
smallest = inf
print(smallest)

inf


In [38]:
import numpy as np

In [40]:
# Eg 10
y = np.zeros(len(x))
y

array([0., 0., 0., 0., 0.])

# WEEK 2

# WEEK 3

In [2]:
import numpy as np

In [8]:
a = np.array([
    [2,3,4],
    [5,3,8],
    [2,0,4]
])
a.sum(axis=0)
a.sum(axis=1)

array([ 9, 16,  6])

In [13]:
b = a.transpose()
b

array([[2, 5, 2],
       [3, 3, 0],
       [4, 8, 4]])

In [14]:
np.add(a,b)

array([[4, 8, 6],
       [8, 6, 8],
       [6, 8, 8]])

In [15]:
np.multiply(a,b)

array([[ 4, 15,  8],
       [15,  9,  0],
       [ 8,  0, 16]])

In [16]:
np.dot(a,b)

array([[29, 51, 20],
       [51, 98, 42],
       [20, 42, 20]])

In [23]:
a = list([[2,3,4],[5,6,7]])
print(type(a))
a = np.array(a, dtype=float)
type(a)
a

<class 'list'>


array([[2., 3., 4.],
       [5., 6., 7.]])

In [24]:
a = tuple([[2,3,4],[5,6,7]])
print(type(a))
a = np.array(a, dtype=float)
type(a)
a

<class 'tuple'>


array([[2., 3., 4.],
       [5., 6., 7.]])

In [27]:
a = np.zeros(shape=(3,4), dtype=int)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [30]:
a = np.arange(start=0,stop=20,step=5)
a

array([ 0,  5, 10, 15])

In [41]:
a = np.linspace(start=4,stop=48,num=12, dtype=int).reshape((2,3,2))
a

array([[[ 4,  8],
        [12, 16],
        [20, 24]],

       [[28, 32],
        [36, 40],
        [44, 48]]])

In [51]:
a = np.array([
    [2,3,4],
    [5,3,8],
    [2,0,4]
])
a.max()
a.min()
for row in a.transpose():
    print(max(row))
a

5
3
8


array([[2, 3, 4],
       [5, 3, 8],
       [2, 0, 4]])